project_id = "wenxswpqgbzwaowdjdqc"

[functions.send-voip-push]
verify_jwt = true

[functions.verify-login-token]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.send-email-relay]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
